GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjhkMjljODVhLWM5MjQtNGY4OS1hMDgzLWNlYmRlZjg2MzkzOSIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwiZnVsbF9uYW1lIjoiYWRtaW4iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NjIzNTQyMzYsImV4cCI6MTc2Mjk1OTAzNn0.vmJXiTiNk5bNd2sSu9w5U6lSsqmYNJmCZoUnmkwGe0c