// // src/services/PhishingDetectorService.js

// /**
//  * Model Naive Bayes Sederhana untuk Deteksi Phishing
//  * Berdasarkan kemunculan kata-kata berbahaya di title & description
//  */

// class PhishingDetectorService {
//   constructor() {
//     // Kata-kata berbahaya yang sering muncul di phishing
//     this.dangerousWords = [
//       "login",
//       "password",
//       "secure",
//       "verify",
//       "account",
//       "bank",
//       "pay",
//       "money",
//       "click",
//       "urgent",
//       "warning",
//       "alert",
//       "confirm",
//       "reset",
//       "update",
//       "admin",
//       "security",
//       "access",
//       "restricted",
//       "suspicious",
//       "fraud",
//       "phish",
//       "hack",
//       "free",
//       "win",
//       "prize",
//       "claim",
//       "reward",
//       "gift",
//       "bonus",
//       "limited",
//       "offer",
//       "expired",
//       "invalid",
//       "locked",
//       "disabled",
//       "suspended",
//       "compromised",
//       "stolen",
//       "ssn",
//       "social security",
//       "credit card",
//       "cvv",
//       "pin",
//       "otp",
//       "2fa",
//       "auth",
//       "verification",
//       "identity",
//       "personal",
//       "confidential",
//       "private",
//       "secret",
//       "support",
//       "help",
//       "service",
//       "customer",
//       "contact",
//       "info",
//       "details",
//       "form",
//       "submit",
//       "register",
//       "sign up",
//       "subscribe",
//       "unsubscribe",
//       "cancel",
//       "delete",
//       "remove",
//       "terminate",
//       "close",
//       "end",
//       "stop",
//       "pause",
//       "resume",
//       "start",
//       "download",
//       "install",
//       "update",
//       "upgrade",
//       "patch",
//       "fix",
//       "repair",
//       "restore",
//       "backup",
//       "recover",
//       "save",
//       "store",
//       "upload",
//       "transfer",
//       "share",
//       "send",
//       "receive",
//       "message",
//       "email",
//       "inbox",
//       "outbox",
//       "spam",
//       "junk",
//       "trash",
//       "delete",
//       "remove",
//       "clear",
//       "empty",
//       "wipe",
//       "erase",
//       "destroy",
//       "corrupt",
//       "virus",
//       "malware",
//       "trojan",
//       "ransomware",
//       "spyware",
//       "adware",
//       "worm",
//       "hacker",
//       "crack",
//       "keygen",
//       "serial",
//       "license",
//       "activation",
//       "registration",
//       "unlock",
//       "bypass",
//       "hack",
//       "cheat",
//       "glitch",
//       "bug",
//       "exploit",
//       "vulnerability",
//       "security breach",
//       "data leak",
//       "information theft",
//       "identity theft",
//       "financial fraud",
//       "credit card fraud",
//       "bank fraud",
//       "payment fraud",
//       "online scam",
//       "internet scam",
//       "email scam",
//       "phone scam",
//       "sms scam",
//       "whatsapp scam",
//       "telegram scam",
//       "facebook scam",
//       "instagram scam",
//       "twitter scam",
//       "linkedin scam",
//       "youtube scam",
//       "tiktok scam",
//       "snapchat scam",
//     ];

//     // Kata-kata aman (opsional, bisa ditambahkan nanti)
//     this.safeWords = [
//       "home",
//       "about",
//       "contact",
//       "blog",
//       "news",
//       "article",
//       "tutorial",
//       "guide",
//       "documentation",
//       "manual",
//       "faq",
//       "help",
//       "support",
//       "community",
//       "forum",
//       "discussion",
//       "comment",
//       "review",
//       "rating",
//       "feedback",
//       "survey",
//       "poll",
//       "vote",
//       "like",
//       "share",
//       "follow",
//       "subscribe",
//       "unsubscribe",
//       "notify",
//       "alert",
//       "reminder",
//       "schedule",
//       "calendar",
//       "event",
//       "meeting",
//       "webinar",
//       "conference",
//       "workshop",
//       "training",
//       "course",
//       "lesson",
//       "video",
//       "audio",
//       "image",
//       "photo",
//       "gallery",
//       "album",
//       "collection",
//       "library",
//       "archive",
//       "history",
//       "timeline",
//       "map",
//       "location",
//       "address",
//       "direction",
//       "route",
//       "transport",
//       "travel",
//       "hotel",
//       "flight",
//       "booking",
//       "reservation",
//       "ticket",
//       "restaurant",
//       "menu",
//       "recipe",
//       "food",
//       "drink",
//       "beverage",
//       "snack",
//       "meal",
//       "shopping",
//       "cart",
//       "checkout",
//       "payment",
//       "invoice",
//       "receipt",
//       "order",
//       "delivery",
//       "shipping",
//       "track",
//       "status",
//       "update",
//       "change",
//       "modify",
//       "edit",
//       "create",
//       "add",
//       "remove",
//       "delete",
//       "cancel",
//       "refund",
//       "return",
//       "exchange",
//       "replace",
//       "repair",
//       "maintain",
//       "service",
//       "support",
//       "help",
//       "contact",
//       "info",
//       "details",
//       "form",
//       "submit",
//       "register",
//       "sign up",
//       "login",
//       "logout",
//       "account",
//       "profile",
//       "settings",
//       "preferences",
//       "privacy",
//       "security",
//       "password",
//       "username",
//       "email",
//       "phone",
//       "address",
//       "name",
//       "age",
//       "gender",
//       "birthday",
//       "interest",
//       "hobby",
//       "skill",
//       "experience",
//       "education",
//       "work",
//       "job",
//       "career",
//       "resume",
//       "cv",
//       "portfolio",
//       "project",
//       "team",
//       "member",
//       "leader",
//       "manager",
//       "director",
//       "executive",
//       "officer",
//       "staff",
//       "employee",
//       "client",
//       "customer",
//       "user",
//       "visitor",
//       "guest",
//       "member",
//       "subscriber",
//       "follower",
//       "fan",
//       "supporter",
//       "contributor",
//       "donor",
//       "sponsor",
//       "partner",
//       "affiliate",
//       "collaborator",
//       "associate",
//       "friend",
//       "acquaintance",
//       "colleague",
//       "companion",
//       "comrade",
//       "ally",
//       "enemy",
//       "opponent",
//       "rival",
//       "competitor",
//       "adversary",
//       "foe",
//       "antagonist",
//       "protagonist",
//       "hero",
//       "villain",
//       "character",
//       "actor",
//       "actress",
//       "star",
//       "celebrity",
//       "influencer",
//       "blogger",
//       "youtuber",
//       "streamer",
//       "gamer",
//       "artist",
//       "musician",
//       "singer",
//       "dancer",
//       "writer",
//       "author",
//       "poet",
//       "novelist",
//       "screenwriter",
//       "playwright",
//       "director",
//       "producer",
//       "editor",
//       "photographer",
//       "videographer",
//       "filmmaker",
//       "designer",
//       "developer",
//       "programmer",
//       "engineer",
//       "scientist",
//       "researcher",
//       "academic",
//       "scholar",
//       "student",
//       "teacher",
//       "professor",
//       "lecturer",
//       "instructor",
//       "tutor",
//       "mentor",
//       "coach",
//       "trainer",
//       "consultant",
//       "advisor",
//       "counselor",
//       "therapist",
//       "psychologist",
//       "psychiatrist",
//       "doctor",
//       "nurse",
//       "midwife",
//       "paramedic",
//       "emergency",
//       "ambulance",
//       "hospital",
//       "clinic",
//       "pharmacy",
//       "medicine",
//       "drug",
//       "pill",
//       "tablet",
//       "capsule",
//       "injection",
//       "vaccine",
//       "immunization",
//       "health",
//       "wellness",
//       "fitness",
//       "exercise",
//       "diet",
//       "nutrition",
//       "weight",
//       "loss",
//       "gain",
//       "maintenance",
//       "body",
//       "mind",
//       "spirit",
//       "soul",
//       "emotion",
//       "feeling",
//       "mood",
//       "attitude",
//       "behavior",
//       "personality",
//       "character",
//       "trait",
//       "quality",
//       "virtue",
//       "vice",
//       "strength",
//       "weakness",
//       "advantage",
//       "disadvantage",
//       "pro",
//       "con",
//       "benefit",
//       "risk",
//       "danger",
//       "threat",
//       "hazard",
//       "peril",
//       "jeopardy",
//       "risk",
//       "uncertainty",
//       "chance",
//       "probability",
//       "likelihood",
//       "odds",
//       "expectation",
//       "prediction",
//       "forecast",
//       "projection",
//       "estimate",
//       "calculation",
//       "measurement",
//       "evaluation",
//       "assessment",
//       "analysis",
//       "synthesis",
//       "integration",
//       "combination",
//       "fusion",
//       "mix",
//       "blend",
//       "merge",
//       "saved",
//       "backed up",
//       "restored",
//       "recovered",
//       "retrieved",
//       "found",
//       "located",
//       "discovered",
//       "identified",
//       "recognized",
//       "acknowledged",
//       "accepted",
//       "rejected",
//       "approved",
//       "denied",
//       "granted",
//       "withheld",
//       "awarded",
//       "punished",
//       "rewarded",
//       "fined",
//       "charged",
//       "billed",
//       "invoiced",
//       "paid",
//       "unpaid",
//       "due",
//       "overdue",
//       "late",
//       "early",
//       "on time",
//       "prompt",
//       "delayed",
//       "postponed",
//       "rescheduled",
//       "cancelled",
//       "aborted",
//       "terminated",
//       "ended",
//       "finished",
//       "completed",
//       "done",
//       "ready",
//       "prepared",
//       "set",
//       "arranged",
//       "organized",
//       "planned",
//       "scheduled",
//       "timed",
//       "dated",
//       "appointed",
//       "assigned",
//       "allocated",
//       "distributed",
//       "shared",
//       "given",
//       "received",
//       "taken",
//       "held",
//       "kept",
//       "stored",
//       "saved",
//       "backed up",
//       "restored",
//       "recovered",
//       "retrieved",
//       "found",
//       "located",
//       "discovered",
//       "identified",
//       "recognized",
//       "acknowledged",
//       "accepted",
//       "rejected",
//       "approved",
//       "denied",
//       "granted",
//       "withheld",
//       "awarded",
//       "punished",
//       "rewarded",
//       "fined",
//       "charged",
//       "billed",
//       "invoiced",
//       "paid",
//       "unpaid",
//       "due",
//       "overdue",
//       "late",
//       "early",
//       "on time",
//       "prompt",
//       "delayed",
//       "postponed",
//       "rescheduled",
//       "cancelled",
//       "aborted",
//       "terminated",
//       "ended",
//     ];
//   }

//   /**
//    * Hitung probabilitas phishing berdasarkan teks
//    * @param {string} text - teks untuk dianalisis (title + description)
//    * @returns {number} probabilitas phishing (0-1)
//    */
//   calculatePhishingProbability(text) {
//     const lowerText = text.toLowerCase();

//     let dangerousCount = 0;
//     let totalWords = 0;

//     // Hitung jumlah kata dalam teks
//     const words = lowerText.match(/\b\w+\b/g) || [];
//     totalWords = words.length;

//     // Hitung jumlah kata berbahaya (match kata utuh, bukan substring)
//     for (const word of this.dangerousWords) {
//       const regex = new RegExp(`\\b${word}\\b`, "g");
//       if (regex.test(lowerText)) {
//         dangerousCount++;
//       }
//     }

//     // Probabilitas sederhana: ratio kata berbahaya / total kata
//     if (totalWords === 0) return 0;

//     let probability = dangerousCount / totalWords;

//     // Tambahkan bobot jika ada kata kunci penting
//     const highRiskKeywords = [
//       "login",
//       "password",
//       "secure",
//       "verify",
//       "bank",
//       "pay",
//       "money",
//     ];
//     for (const keyword of highRiskKeywords) {
//       const regex = new RegExp(`\\b${keyword}\\b`, "g");
//       if (regex.test(lowerText)) {
//         probability += 0.2; // tambah bobot 20%
//       }
//     }

//     // Batasi maksimal 1.0
//     return Math.min(probability, 1.0);
//   }

//   /**
//    * Deteksi apakah link berbahaya
//    * @param {string} title
//    * @param {string} description
//    * @returns {{ isPhishing: boolean, probability: number, message: string }}
//    */
//   detect(title, description) {
//     const combinedText = `${title} ${description}`;
//     const probability = this.calculatePhishingProbability(combinedText);

//     console.log("📝 Deteksi Phishing:");
//     console.log("Title:", title);
//     console.log("Description:", description);
//     console.log("Combined Text:", combinedText);
//     console.log("Probability:", probability);

//     const isPhishing = probability > 0.3;

//     let message = "Link aman";
//     if (isPhishing) {
//       message = `Potensi phishing terdeteksi (${(probability * 100).toFixed(
//         1
//       )}%)`;
//     }

//     return {
//       isPhishing,
//       probability,
//       message,
//     };
//   }
// }

// // Export instance tunggal
// export default new PhishingDetectorService();
